name: scipp code coverage

on: 
  schedule:
    - cron: '0 2 * * *'
  push:
  

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install gcovr
        shell: bash -l {0}
        run: sudo apt install --yes gcovr

      - name: Checkout scipp
        uses: actions/checkout@v2
        with:
          repository: 'scipp/scipp'
          path: repo
          submodules: true
          fetch-depth: 0  # history required so cmake can determine version

      - name: Extend conda env file
        run: echo "  - pytest-cov" >> repo/scipp-developer.yml

      - name: Setup Mambaforge and Scipp dev env
        uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          miniforge-version: latest
          miniforge-variant: Mambaforge
          environment-file: repo/scipp-developer.yml
          activate-environment: scipp-developer
          auto-activate-base: false

      - name: C++ coverage
        shell: bash -l {0}
        run: |
          export PYTHONPATH=$(pwd)/repo/install
          cd repo
          mkdir build
          mkdir install
          mkdir coverage_html
          cd build
          cmake \
            -DCOVERAGE=On \
            -DCMAKE_BUILD_TYPE=Debug \
            -DWITH_CTEST=Off \
            -DDISABLE_MULTI_THREAFING=On \
            -DPython_EXECUTABLE=$(command -v python3) \
            -DCMAKE_INSTALL_PREFIX=../install \
            -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=OFF \
            -DDYNAMIC_LIB=ON \
            ..
          cmake --build . --target coverage VERBOSE=1
          mv coverage ../coverage_html/cpp

      - name: Python coverage
        shell: bash -l {0}
        run: |
          export PYTHONPATH=$(pwd)/repo/install
          cd repo/python/tests
          pytest --cov=scipp --cov-report html:../../coverage_html/python .

      - name: Setup HTML
        shell: bash -l {0}
        run: |
          mv html/index.html repo/coverage_html/

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: repo/coverage_html
