name: scipp code coverage

on: 
  schedule:
    - cron: '0 2 * * *'
  push:
  

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          sudo apt install --yes lcov g++-11
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 100
          sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-11 100
          sudo update-alternatives --set g++ "/usr/bin/g++-11"
          sudo update-alternatives --set gcov "/usr/bin/gcov-11"

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          repository: 'scipp/scipp'
          path: repo
          submodules: true
          fetch-depth: 0  # history required so cmake can determine version

      - name: Setup conda env file
        run: |
          cat repo/scipp-developer.yml | grep -v 'gxx\|tbb' > env.yml
          echo "  - pytest-cov" >> env.yml

      - name: Setup Mambaforge and dev env
        uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          miniforge-version: latest
          miniforge-variant: Mambaforge
          environment-file: env.yml
          activate-environment: scipp-developer
          auto-activate-base: false

      - name: C++ coverage
        shell: bash -l {0}
        run: |
          export PYTHONPATH=$(pwd)/install
          mkdir build
          mkdir install
          mkdir coverage_html
          cd build
          cmake \
            -DCOVERAGE=On \
            -DCMAKE_BUILD_TYPE=Debug \
            -DWITH_CTEST=Off \
            -DDISABLE_MULTI_THREADING=On \
            -DPython_EXECUTABLE=$(command -v python3) \
            -DCMAKE_INSTALL_PREFIX=../install \
            -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=OFF \
            -DDYNAMIC_LIB=ON \
            ../repo
          cmake --build . --target coverage VERBOSE=1
          mv coverage ../coverage_html/cpp

      - name: Python coverage
        shell: bash -l {0}
        run: |
          export PYTHONPATH=$(pwd)/install
          cd repo/python/tests
          pytest --cov=scipp --cov-report html:../../../coverage_html/python .

      - name: Setup HTML
        shell: bash -l {0}
        run: |
          mv html/index.html coverage_html/

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: coverage_html
