name: scipp code coverage

on: 
  schedule:
    - cron: '0 2 * * *'
  push:
  

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install gcovr
        shell: bash -l {0}
        run: sudo apt install --yes lcov

      - name: Checkout scipp
        uses: actions/checkout@v2
        with:
          repository: 'scipp/scipp'
          path: repo
          submodules: true
          fetch-depth: 0  # history required so cmake can determine version

      - name: Extend conda env file
        run: |
          echo "  - pytest-cov" >> repo/scipp-developer.yml
          cat repo/scipp-developer.yml  | grep -v gxx > repo/scipp-developer.yml

      - name: Setup Mambaforge and Scipp dev env
        uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          miniforge-version: latest
          miniforge-variant: Mambaforge
          environment-file: repo/scipp-developer.yml
          activate-environment: scipp-developer
          auto-activate-base: false

      - name: C++ coverage
        shell: bash -l {0}
        run: |
          export PYTHONPATH=$(pwd)/install
          mkdir build
          mkdir install
          mkdir coverage_html
          cd build
          cmake \
            -DCOVERAGE=On \
            -DCMAKE_BUILD_TYPE=Debug \
            -DWITH_CTEST=Off \
            -DDISABLE_MULTI_THREAFING=On \
            -DPython_EXECUTABLE=$(command -v python3) \
            -DCMAKE_INSTALL_PREFIX=../install \
            -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=OFF \
            -DDYNAMIC_LIB=ON \
            ../repo
          cmake --build . --target scipp-units-test VERBOSE=1
          cmake --build . --target scipp-core-test VERBOSE=1
          lcov --zerocounters --directory .
          lcov --no-external --capture --initial --directory . -b ../repo --output-file scipp_base.info
          ./bin/scipp-units-test
          lcov --no-external --capture --directory .  -b ../repo --output-file scipp-units-test.info
          ./bin/scipp-core-test
          lcov --no-external --capture --directory .  -b ../repo --output-file scipp-core-test.info
          lcov -a scipp_base.info -a scipp-units-test.info -a scipp-core-test.info --output-file scipp_total.info
          #lcov --remove scipp_total.info "./core/*.cpp" "./variable/*.cpp" "./dataset/*.cpp" "./python/*.cpp" "/usr/*" "/*conan/data*" "/*miniconda*" --output-file scipp_filtered.info
          genhtml --prefix $(realpath ../repo) --ignore-errors source scipp_total.info --legend --title "$(date)" --output-directory=coverage
          #cmake --build . --target coverage VERBOSE=1
          mv coverage ../coverage_html/cpp

          #- name: Python coverage
          #  shell: bash -l {0}
          #  run: |
          #    export PYTHONPATH=$(pwd)/install
          #    cd repo/python/tests
          #    pytest --cov=scipp --cov-report html:../../../coverage_html/python .

      - name: Setup HTML
        shell: bash -l {0}
        run: |
          mv html/index.html coverage_html/

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: coverage_html
